package cn.aki.demo.entity;

import cn.aki.demo.proxy.IText;

public class TestObject implements IText{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_object.id
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_object.varchar_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	private String varcharValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_object.boolean_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	private Boolean booleanValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_object.text_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_object.id
	 * @return  the value of test_object.id
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_object.id
	 * @param id  the value for test_object.id
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_object.varchar_value
	 * @return  the value of test_object.varchar_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public String getVarcharValue() {
		return varcharValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_object.varchar_value
	 * @param varcharValue  the value for test_object.varchar_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public void setVarcharValue(String varcharValue) {
		this.varcharValue = varcharValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_object.boolean_value
	 * @return  the value of test_object.boolean_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public Boolean getBooleanValue() {
		return booleanValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_object.boolean_value
	 * @param booleanValue  the value for test_object.boolean_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public void setBooleanValue(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_object.text_value
	 * @return  the value of test_object.text_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_object.text_value
	 * @param text  the value for test_object.text_value
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	public void setText(String text) {
		this.text = text;
	}
}