package cn.aki.demo.dao;

import cn.aki.demo.entity.TestObject;
import cn.aki.demo.entity.TestObjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestObjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	long countByExample(TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int deleteByExample(TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int insert(TestObject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int insertSelective(TestObject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	List<TestObject> selectByExampleWithBLOBs(TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	List<TestObject> selectByExample(TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	TestObject selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TestObject record, @Param("example") TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TestObject record, @Param("example") TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByExample(@Param("record") TestObject record, @Param("example") TestObjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByPrimaryKeySelective(TestObject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TestObject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_object
	 * @mbg.generated  Thu May 11 15:24:11 CST 2017
	 */
	int updateByPrimaryKey(TestObject record);
}